import { NavbarComponent } from "@/components/navbar";
import { SessionProviders } from "@/components/SessionProvider";
import { Toaster } from "@/components/ui/toaster";
import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <SessionProviders>
          <NavbarComponent />
          {children}
        </SessionProviders>
        <Toaster />
      </body>
    </html>
  );
}
